# Generated by Django 5.0.7 on 2024-10-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the customer')),
                ('email', models.EmailField(max_length=254, verbose_name='Email of the customer')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform')),
                ('orders', models.IntegerField(default=0, verbose_name='Total Orders')),
                ('returns', models.IntegerField(default=0, verbose_name='No.of returns')),
                ('deliveries', models.IntegerField(default=0, verbose_name='No.of deliveries')),
            ],
        ),
    ]
