# Generated by Django 5.0.7 on 2024-10-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_analytics', '0002_flipkartdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
