# Generated by Django 5.0.7 on 2024-10-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_analytics', '0003_delete_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flipkartdata',
            table='flipkart_data',
        ),
    ]
